#!/bin/bash

# ============================================================
#  xray-manager
#  Commands: setup | create | print [username] | export
# ============================================================

set -e

# ============================================================
#  Default Variables — edit these or override at runtime
#  These are also saved/loaded from SAVED_VARS_FILE after setup
# ============================================================
CONFIG="/usr/local/etc/xray/config.json"
NGINX_SITES="/etc/nginx/sites-available"
NGINX_ENABLED="/etc/nginx/sites-enabled"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SAVED_VARS_FILE="${SCRIPT_DIR}/xray-manager.conf"
EXPORT_FILE="$HOME/xray-configs.txt"

DEFAULT_SERVER_IP=""
DEFAULT_CDN_DOMAIN="bazi.bazistation.online"
DEFAULT_VMESS_HOST="varzesh3.com"
DEFAULT_REALITY_SNI="varzesh3.com"
DEFAULT_CDN_PORT="443"
DEFAULT_VMESS_PORT="8080"
DEFAULT_REALITY_PORT="8443"
VLESS_WS_PATH="/slark"
VLESS_GRPC_SERVICE="slarkg"
VMESS_PATH="/18E114BB-6E68-48E1-9A18-82B2C187403F"

# Xray internal listen ports (nginx proxies to these)
XRAY_VLESS_WS_PORT="10000"
XRAY_VLESS_GRPC_PORT="10001"
XRAY_VMESS_PORT="10080"
# ============================================================

# ---------- Colors ----------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# ---------- Load saved vars (written by setup) ----------
load_saved_vars() {
  if [ -f "$SAVED_VARS_FILE" ]; then
    # shellcheck source=/dev/null
    source "$SAVED_VARS_FILE"
  fi
}

# ---------- Save vars to file ----------
save_vars() {
  cat > "$SAVED_VARS_FILE" <<EOF
# Xray Manager — saved defaults (generated by setup on $(date))
DEFAULT_SERVER_IP="$DEFAULT_SERVER_IP"
DEFAULT_CDN_DOMAIN="$DEFAULT_CDN_DOMAIN"
DEFAULT_VMESS_HOST="$DEFAULT_VMESS_HOST"
DEFAULT_REALITY_SNI="$DEFAULT_REALITY_SNI"
DEFAULT_CDN_PORT="$DEFAULT_CDN_PORT"
DEFAULT_VMESS_PORT="$DEFAULT_VMESS_PORT"
DEFAULT_REALITY_PORT="$DEFAULT_REALITY_PORT"
VLESS_WS_PATH="$VLESS_WS_PATH"
VLESS_GRPC_SERVICE="$VLESS_GRPC_SERVICE"
VMESS_PATH="$VMESS_PATH"
XRAY_VLESS_WS_PORT="$XRAY_VLESS_WS_PORT"
XRAY_VLESS_GRPC_PORT="$XRAY_VLESS_GRPC_PORT"
XRAY_VMESS_PORT="$XRAY_VMESS_PORT"
EOF
  echo -e "${GREEN}Defaults saved to ${SAVED_VARS_FILE}${NC}"
}

# ---------- Usage ----------
usage() {
  echo -e "${BOLD}Usage:${NC}"
  echo -e "  $0 setup               — First-time server setup (nginx + xray skeleton + certbot)"
  echo -e "  $0 create              — Add a new user"
  echo -e "  $0 print               — Print configs for ALL users"
  echo -e "  $0 print <username>    — Print configs for a specific user"
  echo -e "  $0 export              — Export all configs to ${EXPORT_FILE}"
  echo ""
  exit 1
}

# ---------- Auto-install a package via apt ----------
ensure_apt_pkg() {
  local cmd="$1" pkg="${2:-$1}"
  if ! command -v "$cmd" &>/dev/null; then
    echo -e "${CYAN}Installing ${pkg}...${NC}"
    apt-get update -qq && apt-get install -y -qq "$pkg"       && echo -e "${GREEN}${pkg} installed.${NC}"       || { echo -e "${RED}Failed to install ${pkg}. Install manually and re-run.${NC}"; exit 1; }
  fi
}

# ---------- Check / auto-install deps ----------
check_deps() {
  # Always needed
  ensure_apt_pkg jq
  ensure_apt_pkg openssl

  if [ "${1:-}" == "create" ]; then
    if ! command -v uuidgen &>/dev/null; then
      ensure_apt_pkg uuidgen uuid-runtime
    fi
    if ! command -v xray &>/dev/null; then
      echo -e "${RED}Error: 'xray' is not installed.${NC}"
      echo -e "${YELLOW}Install it with: bash -c \"$(curl -L https://github.com/XTLS/Xray-install/raw/main/install-release.sh)\" @ install${NC}"
      exit 1
    fi
  fi

  if [ "${1:-}" == "setup" ]; then
    ensure_apt_pkg nginx
    # certbot via snap is preferred but fall back to apt
    if ! command -v certbot &>/dev/null; then
      echo -e "${CYAN}Installing certbot...${NC}"
      if command -v snap &>/dev/null; then
        snap install --classic certbot           && ln -sf /snap/bin/certbot /usr/bin/certbot           && echo -e "${GREEN}certbot installed via snap.${NC}"
      else
        ensure_apt_pkg certbot
        ensure_apt_pkg python3-certbot-nginx
      fi
    fi
  fi

  if [ "${1:-}" != "setup" ] && config_needs_skeleton; then
    echo -e "${RED}Error: Xray config not found or empty at $CONFIG${NC}"
    echo -e "${YELLOW}Run '$0 setup' first.${NC}"
    exit 1
  fi
}

# ---------- Get server IP ----------
get_server_ip() {
  if [ -n "$DEFAULT_SERVER_IP" ]; then
    SERVER_IP="$DEFAULT_SERVER_IP"
  else
    read -rp "$(echo -e ${YELLOW}"Enter your server public IP: "${NC})" SERVER_IP
    if [ -z "$SERVER_IP" ]; then
      echo -e "${RED}Server IP cannot be empty.${NC}"; exit 1
    fi
  fi
}

# ---------- Build links for a user ----------
build_links() {
  local user="$1" uuid="$2" ip="$3" cdn="$4" vmhost="$5" rsni="$6" pubkey="$7" sid="$8"

  LINK_WS="vless://${uuid}@${cdn}:${DEFAULT_CDN_PORT}?encryption=none&security=tls&sni=${cdn}&insecure=0&allowInsecure=0&type=ws&host=${cdn}&path=%2F${VLESS_WS_PATH##/}#${user}_WS_CDN"

  LINK_GRPC="vless://${uuid}@${cdn}:${DEFAULT_CDN_PORT}?encryption=none&security=tls&sni=${cdn}&insecure=0&type=grpc&serviceName=${VLESS_GRPC_SERVICE}#${user}_gRPC_CDN"

  local vmess_json
  vmess_json=$(printf '{"v":"2","ps":"%s_VMess","add":"%s","port":"%s","id":"%s","aid":"0","scy":"auto","net":"httpupgrade","type":"none","host":"%s","path":"%s","tls":"","sni":"","alpn":""}' \
    "$user" "$ip" "$DEFAULT_VMESS_PORT" "$uuid" "$vmhost" "$VMESS_PATH")
  LINK_VMESS="vmess://$(echo "$vmess_json" | base64 -w 0)"

  if [ -n "$pubkey" ] && [ -n "$sid" ]; then
    LINK_REALITY="vless://${uuid}@${ip}:${DEFAULT_REALITY_PORT}?encryption=none&security=reality&sni=${rsni}&fp=chrome&pbk=${pubkey}&sid=${sid}&type=tcp&flow=xtls-rprx-vision#${user}_Reality"
  else
    LINK_REALITY="(Reality key/shortId not found in config)"
  fi
}

# ---------- Print links (colored) ----------
print_user_links() {
  local user="$1"
  echo -e "\n${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${BOLD}  User: ${GREEN}${user}${NC}"
  echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${BOLD}[1] VLESS + WebSocket + TLS + CDN${NC}"
  echo -e "${DIM}${LINK_WS}${NC}\n"
  echo -e "${BOLD}[2] VLESS + gRPC + TLS + CDN${NC}"
  echo -e "${DIM}${LINK_GRPC}${NC}\n"
  echo -e "${BOLD}[3] VMess + HTTPUpgrade${NC}"
  echo -e "${DIM}${LINK_VMESS}${NC}\n"
  echo -e "${BOLD}[4] VLESS + Reality${NC}"
  echo -e "${DIM}${LINK_REALITY}${NC}"
}

# ---------- Format user block (plain text) ----------
format_user_block() {
  local user="$1"
  cat <<EOF

============================================================
  User: ${user}
============================================================

[1] VLESS + WebSocket + TLS + CDN
${LINK_WS}

[2] VLESS + gRPC + TLS + CDN
${LINK_GRPC}

[3] VMess + HTTPUpgrade
${LINK_VMESS}

[4] VLESS + Reality
${LINK_REALITY}

EOF
}

# ---------- Resolve user from config ----------
resolve_user() {
  local username="$1"

  R_UUID=$(jq -r --arg u "$username" '
    .inbounds[] | select(.tag == "vless-ws") |
    .settings.clients[] | select(.email == $u) | .id
  ' "$CONFIG" 2>/dev/null || true)

  if [ -z "$R_UUID" ]; then
    R_UUID=$(jq -r --arg u "$username" '
      [.inbounds[].settings.clients[]? | select(.email == $u) | .id] | first
    ' "$CONFIG" 2>/dev/null || true)
  fi

  R_PUBKEY=$(jq -r '
    .inbounds[] | select(.tag == "vless-reality") |
    .streamSettings.realitySettings |
    if has("publicKey") then .publicKey else "PUBKEY_NOT_IN_CONFIG" end
  ' "$CONFIG" 2>/dev/null | head -1 || true)

  R_SHORTID=$(jq -r --arg u "${username}-reality" '
    .inbounds[] | select(.tag == "vless-reality") |
    .streamSettings.realitySettings.shortIds | last
  ' "$CONFIG" 2>/dev/null || true)

  R_RSNI=$(jq -r '
    .inbounds[] | select(.tag == "vless-reality") |
    .streamSettings.realitySettings.serverNames[0]
  ' "$CONFIG" 2>/dev/null || true)
  R_RSNI="${R_RSNI:-$DEFAULT_REALITY_SNI}"

  R_CDN="$DEFAULT_CDN_DOMAIN"
  R_VMHOST="$DEFAULT_VMESS_HOST"
  R_IP="${DEFAULT_SERVER_IP}"

  if [ -z "$R_IP" ]; then
    read -rp "$(echo -e ${YELLOW}"Enter server public IP (needed for VMess/Reality links): "${NC})" R_IP
  fi
}

# ---------- Get all usernames ----------
get_all_users() {
  jq -r '[.inbounds[].settings.clients[]?.email] | unique | .[]' "$CONFIG" 2>/dev/null \
    | grep -v '\-reality$' | sort
}

# ---------- Xray config helpers ----------
config_needs_skeleton() {
  if [ ! -f "$CONFIG" ]; then return 0; fi
  if [ ! -s "$CONFIG" ]; then return 0; fi
  if ! jq empty "$CONFIG" 2>/dev/null; then return 0; fi
  local count
  count=$(jq '[.inbounds[]? | select(.tag == "vless-ws" or .tag == "vless-grpc" or .tag == "inbound-80")] | length' "$CONFIG" 2>/dev/null || echo 0)
  [ "$count" -lt 3 ]
}

write_xray_config_skeleton() {
  cat > "$CONFIG" <<EOF
{
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query",
      "https+local://8.8.8.8/dns-query",
      "1.1.1.1"
    ]
  },
  "inbounds": [
    {
      "listen": "127.0.0.1",
      "port": ${XRAY_VLESS_GRPC_PORT},
      "protocol": "vless",
      "settings": { "clients": [], "decryption": "none" },
      "streamSettings": {
        "network": "grpc",
        "security": "none",
        "grpcSettings": { "serviceName": "${VLESS_GRPC_SERVICE}" }
      },
      "tag": "vless-grpc"
    },
    {
      "listen": "127.0.0.1",
      "port": ${XRAY_VLESS_WS_PORT},
      "protocol": "vless",
      "settings": { "clients": [], "decryption": "none" },
      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": { "path": "${VLESS_WS_PATH}" }
      },
      "tag": "vless-ws"
    },
    {
      "listen": "127.0.0.1",
      "port": ${XRAY_VMESS_PORT},
      "protocol": "vmess",
      "settings": { "clients": [] },
      "streamSettings": {
        "network": "httpupgrade",
        "httpupgradeSettings": {
          "path": "${VMESS_PATH}",
          "host": "${DEFAULT_VMESS_HOST}"
        }
      },
      "tag": "inbound-80"
    }
  ],
  "outbounds": [
    { "protocol": "freedom", "tag": "direct" }
  ]
}
EOF
}

ensure_xray_config() {
  if [ -f "$CONFIG" ] && [ -s "$CONFIG" ]; then
    cp "$CONFIG" "${CONFIG}.bak.$(date +%Y%m%d%H%M%S)"
    echo -e "${YELLOW}Existing config backed up.${NC}"
  fi
  if config_needs_skeleton; then
    write_xray_config_skeleton
    echo -e "${GREEN}Xray config skeleton written to $CONFIG${NC}"
    return 0
  fi
  echo -e "${GREEN}Using existing Xray config at $CONFIG${NC}"
}

# ---------- TLS cert helpers ----------
cert_exists() {
  [ -f "/etc/letsencrypt/live/${DEFAULT_CDN_DOMAIN}/fullchain.pem" ] \
    && [ -f "/etc/letsencrypt/live/${DEFAULT_CDN_DOMAIN}/privkey.pem" ]
}

write_nginx_tls_site() {
  cat > "$NGINX_TLS_SITE" <<EOF
server {
    listen ${DEFAULT_CDN_PORT} ssl http2;
    server_name ${DEFAULT_CDN_DOMAIN};

    ssl_certificate     /etc/letsencrypt/live/${DEFAULT_CDN_DOMAIN}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${DEFAULT_CDN_DOMAIN}/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # VLESS + WebSocket
    location ${VLESS_WS_PATH} {
        proxy_redirect off;
        proxy_pass http://127.0.0.1:${XRAY_VLESS_WS_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_buffering off;
        proxy_read_timeout 86400;
    }

    # VLESS + gRPC
    location /${VLESS_GRPC_SERVICE} {
        grpc_pass grpc://127.0.0.1:${XRAY_VLESS_GRPC_PORT};
        grpc_set_header Host \$host;
        grpc_set_header X-Real-IP \$remote_addr;
        grpc_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        grpc_read_timeout 86400s;
        grpc_send_timeout 86400s;
        grpc_buffer_size 4k;
    }

    # Block everything else
    location / {
        return 404;
    }
}
EOF
}

write_nginx_tls_bootstrap() {
  local webroot="/var/www/certbot"
  mkdir -p "$webroot"
  cat > "$NGINX_TLS_SITE" <<EOF
server {
    listen 80;
    server_name ${DEFAULT_CDN_DOMAIN};

    location /.well-known/acme-challenge/ {
        root ${webroot};
    }

    location / {
        return 404;
    }
}
EOF
}

reload_nginx_if_ok() {
  if nginx -t 2>/dev/null; then
    systemctl reload nginx && echo -e "${GREEN}Nginx reloaded.${NC}"
    return 0
  fi
  echo -e "${RED}Nginx config test failed — please fix before reloading.${NC}"
  nginx -t
  return 1
}

# ============================================================
#  COMMAND: setup
# ============================================================
cmd_setup() {
  check_deps "setup"

  echo -e "${CYAN}${BOLD}"
  echo "================================================"
  echo "       Xray Manager — First-Time Setup         "
  echo "================================================"
  echo -e "${NC}"

  # ---- Collect all settings ----
  read -rp "$(echo -e ${YELLOW}"Server public IP: "${NC})" DEFAULT_SERVER_IP
  [ -z "$DEFAULT_SERVER_IP" ] && { echo -e "${RED}IP required.${NC}"; exit 1; }

  read -rp "$(echo -e ${YELLOW}"CDN domain for VLESS+WS+gRPC (default: ${DEFAULT_CDN_DOMAIN}): "${NC})" _in
  DEFAULT_CDN_DOMAIN="${_in:-$DEFAULT_CDN_DOMAIN}"

  read -rp "$(echo -e ${YELLOW}"VMess host / nginx server_name (default: ${DEFAULT_VMESS_HOST}): "${NC})" _in
  DEFAULT_VMESS_HOST="${_in:-$DEFAULT_VMESS_HOST}"

  read -rp "$(echo -e ${YELLOW}"Reality SNI domain (default: ${DEFAULT_REALITY_SNI}): "${NC})" _in
  DEFAULT_REALITY_SNI="${_in:-$DEFAULT_REALITY_SNI}"

  echo ""
  echo -e "${BOLD}--- Ports ---${NC}"
  read -rp "$(echo -e ${YELLOW}"CDN/TLS public port (default: ${DEFAULT_CDN_PORT}): "${NC})" _in
  DEFAULT_CDN_PORT="${_in:-$DEFAULT_CDN_PORT}"

  read -rp "$(echo -e ${YELLOW}"VMess public port (default: ${DEFAULT_VMESS_PORT}): "${NC})" _in
  DEFAULT_VMESS_PORT="${_in:-$DEFAULT_VMESS_PORT}"

  read -rp "$(echo -e ${YELLOW}"Reality direct port (default: ${DEFAULT_REALITY_PORT}): "${NC})" _in
  DEFAULT_REALITY_PORT="${_in:-$DEFAULT_REALITY_PORT}"

  echo ""
  echo -e "${BOLD}--- Xray internal listen ports (nginx → xray) ---${NC}"
  read -rp "$(echo -e ${YELLOW}"Xray VLESS-WS internal port (default: ${XRAY_VLESS_WS_PORT}): "${NC})" _in
  XRAY_VLESS_WS_PORT="${_in:-$XRAY_VLESS_WS_PORT}"

  read -rp "$(echo -e ${YELLOW}"Xray VLESS-gRPC internal port (default: ${XRAY_VLESS_GRPC_PORT}): "${NC})" _in
  XRAY_VLESS_GRPC_PORT="${_in:-$XRAY_VLESS_GRPC_PORT}"

  read -rp "$(echo -e ${YELLOW}"Xray VMess internal port (default: ${XRAY_VMESS_PORT}): "${NC})" _in
  XRAY_VMESS_PORT="${_in:-$XRAY_VMESS_PORT}"

  echo ""
  echo -e "${BOLD}--- Paths ---${NC}"
  read -rp "$(echo -e ${YELLOW}"VLESS WebSocket path (default: ${VLESS_WS_PATH}): "${NC})" _in
  VLESS_WS_PATH="${_in:-$VLESS_WS_PATH}"
  # ensure leading slash
  [[ "$VLESS_WS_PATH" != /* ]] && VLESS_WS_PATH="/$VLESS_WS_PATH"

  read -rp "$(echo -e ${YELLOW}"VLESS gRPC service name (default: ${VLESS_GRPC_SERVICE}): "${NC})" _in
  VLESS_GRPC_SERVICE="${_in:-$VLESS_GRPC_SERVICE}"

  read -rp "$(echo -e ${YELLOW}"VMess HTTPUpgrade path (default: ${VMESS_PATH}): "${NC})" _in
  VMESS_PATH="${_in:-$VMESS_PATH}"
  [[ "$VMESS_PATH" != /* ]] && VMESS_PATH="/$VMESS_PATH"

  # ---- Save defaults ----
  save_vars

  # ---- Create xray config dir and skeleton ----
  echo -e "\n${CYAN}Creating Xray config skeleton...${NC}"
  mkdir -p "$(dirname "$CONFIG")"
  ensure_xray_config

  # ---- Write nginx site: TLS (VLESS WS + gRPC) ----
  echo -e "\n${CYAN}Writing nginx site: TLS (VLESS WS + gRPC)...${NC}"
  NGINX_TLS_SITE="${NGINX_SITES}/${DEFAULT_CDN_DOMAIN}.conf"
  if cert_exists; then
    write_nginx_tls_site
    echo -e "${GREEN}Written (TLS): ${NGINX_TLS_SITE}${NC}"
  else
    write_nginx_tls_bootstrap
    echo -e "${GREEN}Written (HTTP bootstrap for certbot): ${NGINX_TLS_SITE}${NC}"
    echo -e "${YELLOW}Port 80 is used temporarily until Let's Encrypt issues a certificate.${NC}"
  fi

  # ---- Write nginx site: VMess HTTPUpgrade (plain HTTP) ----
  echo -e "\n${CYAN}Writing nginx site: VMess HTTPUpgrade...${NC}"
  NGINX_VMESS_SITE="${NGINX_SITES}/${DEFAULT_VMESS_HOST}.conf"
  cat > "$NGINX_VMESS_SITE" <<EOF
server {
    listen ${DEFAULT_VMESS_PORT};
    server_name ${DEFAULT_VMESS_HOST} _;

    # Drop everything else fast
    location / {
        return 444;
    }

    # VMess HTTPUpgrade endpoint
    location = ${VMESS_PATH} {
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_set_header Host \$http_host;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:${XRAY_VMESS_PORT};
    }
}
EOF
  echo -e "${GREEN}Written: ${NGINX_VMESS_SITE}${NC}"

  # ---- Enable sites ----
  echo -e "\n${CYAN}Enabling nginx sites...${NC}"
  ln -sf "$NGINX_TLS_SITE"   "${NGINX_ENABLED}/$(basename $NGINX_TLS_SITE)"
  ln -sf "$NGINX_VMESS_SITE" "${NGINX_ENABLED}/$(basename $NGINX_VMESS_SITE)"

  # ---- Open firewall ports ----
  echo -e "\n${CYAN}Opening firewall ports...${NC}"
  FIREWALL_PORTS=("$DEFAULT_CDN_PORT" "$DEFAULT_VMESS_PORT" "$DEFAULT_REALITY_PORT")
  if ! cert_exists; then
    FIREWALL_PORTS+=("80")
  fi
  for port in "${FIREWALL_PORTS[@]}"; do
    if ufw status | grep -q "Status: active"; then
      ufw allow "${port}/tcp" && echo -e "${GREEN}Opened port ${port}/tcp${NC}"
    else
      echo -e "${YELLOW}ufw not active — skipping port ${port}${NC}"
    fi
  done

  # ---- Start nginx (bootstrap config must load before certbot) ----
  echo -e "\n${CYAN}Testing nginx config...${NC}"
  reload_nginx_if_ok || true

  # ---- Run certbot ----
  echo -e "\n${CYAN}SSL Certificate for ${DEFAULT_CDN_DOMAIN}${NC}"
  echo -e "${YELLOW}Note: DNS for ${DEFAULT_CDN_DOMAIN} must point to this server and port 80 must be reachable.${NC}"
  if cert_exists; then
    echo -e "${GREEN}Certificate already present — skipping certbot.${NC}"
  else
    read -rp "$(echo -e ${YELLOW}"Run certbot now? [y/N]: "${NC})" _run_certbot
    if [[ "$_run_certbot" =~ ^[Yy]$ ]]; then
      read -rp "$(echo -e ${YELLOW}"Email for certbot notifications (required): "${NC})" CERTBOT_EMAIL
      if [ -z "$CERTBOT_EMAIL" ]; then
        echo -e "${RED}Email is required for certbot. Skipping certificate issuance.${NC}"
        echo -e "${YELLOW}Run manually: certbot certonly --webroot -w /var/www/certbot -d ${DEFAULT_CDN_DOMAIN} --email you@example.com --agree-tos${NC}"
      elif certbot certonly --webroot -w /var/www/certbot -d "$DEFAULT_CDN_DOMAIN" \
        --non-interactive --agree-tos --email "$CERTBOT_EMAIL"; then
        echo -e "${GREEN}Certificate issued for ${DEFAULT_CDN_DOMAIN}${NC}"
        write_nginx_tls_site
        echo -e "${GREEN}Updated nginx site to TLS: ${NGINX_TLS_SITE}${NC}"
      else
        echo -e "${RED}Certbot failed — nginx is still on the HTTP bootstrap config.${NC}"
        echo -e "${YELLOW}Fix DNS/firewall, then run manually:${NC}"
        echo -e "  certbot certonly --webroot -w /var/www/certbot -d ${DEFAULT_CDN_DOMAIN} --email ${CERTBOT_EMAIL} --agree-tos"
        echo -e "${YELLOW}After the certificate is issued, re-run: $0 setup${NC}"
      fi
    else
      echo -e "${YELLOW}Skipped certbot. Nginx is on the HTTP bootstrap config until a certificate exists.${NC}"
      echo -e "${YELLOW}Run manually:${NC}"
      echo -e "  certbot certonly --webroot -w /var/www/certbot -d ${DEFAULT_CDN_DOMAIN} --email you@example.com --agree-tos"
      echo -e "${YELLOW}Then re-run: $0 setup${NC}"
    fi
  fi

  # ---- Test and reload nginx ----
  echo -e "\n${CYAN}Testing nginx config...${NC}"
  reload_nginx_if_ok || true

  # ---- Restart xray ----
  echo -e "\n${CYAN}Starting Xray...${NC}"
  if systemctl restart xray 2>/dev/null; then
    echo -e "${GREEN}Xray started.${NC}"
  else
    echo -e "${YELLOW}Could not start Xray — start manually: systemctl start xray${NC}"
  fi

  echo -e "\n${BOLD}${GREEN}================================================${NC}"
  echo -e "${BOLD}${GREEN}   Setup complete!                              ${NC}"
  echo -e "${BOLD}${GREEN}================================================${NC}"
  echo -e "  Xray config  : ${CONFIG}"
  echo -e "  TLS nginx    : ${NGINX_TLS_SITE}"
  echo -e "  VMess nginx  : ${NGINX_VMESS_SITE}"
  echo -e "  Saved vars   : ${SAVED_VARS_FILE}"
  echo -e "\nRun ${BOLD}$0 create${NC} to add your first user.\n"
}

# ============================================================
#  COMMAND: create
# ============================================================
cmd_create() {
  check_deps "create"

  if config_needs_skeleton; then
    echo -e "${RED}Error: Xray config at $CONFIG is missing or empty.${NC}"
    echo -e "${YELLOW}Run '$0 setup' first to create the config skeleton.${NC}"
    exit 1
  fi

  echo -e "${CYAN}${BOLD}"
  echo "================================================"
  echo "         Xray User Manager — Create User       "
  echo "================================================"
  echo -e "${NC}"

  read -rp "$(echo -e ${YELLOW}"Enter new username (e.g. john): "${NC})" USERNAME
  USERNAME="${USERNAME// /_}"
  if [ -z "$USERNAME" ]; then
    echo -e "${RED}Username cannot be empty.${NC}"; exit 1
  fi

  if jq -e --arg u "$USERNAME" '.inbounds[].settings.clients[]? | select(.email == $u)' "$CONFIG" > /dev/null 2>&1; then
    echo -e "${RED}User '$USERNAME' already exists in the config.${NC}"
    echo -e "${YELLOW}Use: $0 print $USERNAME  to view their configs.${NC}"
    exit 1
  fi

  get_server_ip
  read -rp "$(echo -e ${YELLOW}"CDN domain (default: ${DEFAULT_CDN_DOMAIN}): "${NC})" _in
  CDN_DOMAIN="${_in:-$DEFAULT_CDN_DOMAIN}"
  read -rp "$(echo -e ${YELLOW}"VMess HTTPUpgrade host (default: ${DEFAULT_VMESS_HOST}): "${NC})" _in
  VMESS_HOST="${_in:-$DEFAULT_VMESS_HOST}"
  read -rp "$(echo -e ${YELLOW}"Reality SNI domain (default: ${DEFAULT_REALITY_SNI}): "${NC})" _in
  REALITY_SNI="${_in:-$DEFAULT_REALITY_SNI}"

  UUID=$(cat /proc/sys/kernel/random/uuid 2>/dev/null || uuidgen | tr '[:upper:]' '[:lower:]')

  echo -e "\n${CYAN}Generating Reality keypair...${NC}"
  KEYPAIR=$(xray x25519)
  PRIVATE_KEY=$(echo "$KEYPAIR" | grep "Private key" | awk '{print $3}')
  PUBLIC_KEY=$(echo "$KEYPAIR" | grep "Public key" | awk '{print $3}')
  SHORT_ID=$(openssl rand -hex 8)

  echo -e "${GREEN}UUID:${NC}                $UUID"
  echo -e "${GREEN}Reality Public Key:${NC}  $PUBLIC_KEY"
  echo -e "${GREEN}Reality Short ID:${NC}    $SHORT_ID"

  cp "$CONFIG" "${CONFIG}.bak.$(date +%Y%m%d%H%M%S)"
  echo -e "\n${CYAN}Config backed up.${NC}"

  add_client_to_inbound() {
    local tag="$1" client_json="$2"
    local idx
    idx=$(jq --arg tag "$tag" '.inbounds | map(.tag == $tag) | index(true)' "$CONFIG")
    if [ "$idx" == "null" ]; then
      echo -e "${YELLOW}Warning: inbound tag '$tag' not found, skipping.${NC}"; return
    fi
    jq --argjson client "$client_json" --arg tag "$tag" \
      '(.inbounds[] | select(.tag == $tag) | .settings.clients) += [$client]' \
      "$CONFIG" > "${CONFIG}.tmp" && mv "${CONFIG}.tmp" "$CONFIG"
  }

  add_client_to_inbound "vless-ws"   "{\"id\": \"$UUID\", \"email\": \"$USERNAME\"}"
  add_client_to_inbound "vless-grpc" "{\"id\": \"$UUID\", \"email\": \"$USERNAME\"}"
  add_client_to_inbound "inbound-80" "{\"id\": \"$UUID\", \"alterId\": 0, \"security\": \"auto\", \"email\": \"$USERNAME\"}"

  REALITY_TAG="vless-reality"
  REALITY_IDX=$(jq --arg tag "$REALITY_TAG" '.inbounds | map(.tag == $tag) | index(true)' "$CONFIG")

  if [ "$REALITY_IDX" == "null" ]; then
    echo -e "${CYAN}Creating Reality inbound on port ${DEFAULT_REALITY_PORT}...${NC}"
    REALITY_INBOUND=$(cat <<EOF
{
  "listen": "0.0.0.0",
  "port": ${DEFAULT_REALITY_PORT},
  "protocol": "vless",
  "settings": {
    "clients": [
      {"id": "$UUID", "email": "${USERNAME}-reality", "flow": "xtls-rprx-vision"}
    ],
    "decryption": "none"
  },
  "streamSettings": {
    "network": "tcp",
    "security": "reality",
    "realitySettings": {
      "show": false,
      "dest": "${REALITY_SNI}:443",
      "serverNames": ["$REALITY_SNI"],
      "privateKey": "$PRIVATE_KEY",
      "publicKey": "$PUBLIC_KEY",
      "shortIds": ["$SHORT_ID"]
    }
  },
  "sniffing": {"enabled": true, "destOverride": ["http","tls","quic"]},
  "tag": "vless-reality"
}
EOF
)
    jq --argjson inbound "$REALITY_INBOUND" '.inbounds += [$inbound]' \
      "$CONFIG" > "${CONFIG}.tmp" && mv "${CONFIG}.tmp" "$CONFIG"
  else
    add_client_to_inbound "vless-reality" \
      "{\"id\": \"$UUID\", \"email\": \"${USERNAME}-reality\", \"flow\": \"xtls-rprx-vision\"}"
    jq --arg sid "$SHORT_ID" --arg tag "$REALITY_TAG" \
      '(.inbounds[] | select(.tag == $tag) | .streamSettings.realitySettings.shortIds) += [$sid]' \
      "$CONFIG" > "${CONFIG}.tmp" && mv "${CONFIG}.tmp" "$CONFIG"
    echo -e "${YELLOW}Reality inbound exists — user and shortId appended.${NC}"
    PUBLIC_KEY=$(jq -r '.inbounds[] | select(.tag=="vless-reality") | .streamSettings.realitySettings.publicKey' "$CONFIG" 2>/dev/null || echo "$PUBLIC_KEY")
  fi

  echo -e "\n${CYAN}Restarting Xray...${NC}"
  if systemctl restart xray 2>/dev/null; then
    echo -e "${GREEN}Xray restarted.${NC}"
  else
    echo -e "${YELLOW}Could not restart Xray — please restart manually.${NC}"
  fi

  build_links "$USERNAME" "$UUID" "$SERVER_IP" "$CDN_DOMAIN" "$VMESS_HOST" "$REALITY_SNI" "$PUBLIC_KEY" "$SHORT_ID"
  print_user_links "$USERNAME"

  OUTPUT_FILE="/root/xray_user_${USERNAME}.txt"
  {
    echo "Generated: $(date)"
    format_user_block "$USERNAME"
    echo "Reality Private Key : $PRIVATE_KEY"
    echo "Reality Public Key  : $PUBLIC_KEY"
    echo "Reality Short ID    : $SHORT_ID"
  } > "$OUTPUT_FILE"

  echo -e "\n${GREEN}Saved to: ${BOLD}${OUTPUT_FILE}${NC}\n"
}

# ============================================================
#  COMMAND: print
# ============================================================
cmd_print() {
  check_deps
  get_server_ip

  if [ -n "${1:-}" ]; then
    local username="$1"
    resolve_user "$username"
    if [ -z "$R_UUID" ]; then
      echo -e "${RED}User '$username' not found in config.${NC}"
      echo -e "${YELLOW}Use: $0 create  to add them.${NC}"
      exit 1
    fi
    build_links "$username" "$R_UUID" "$R_IP" "$R_CDN" "$R_VMHOST" "$R_RSNI" "$R_PUBKEY" "$R_SHORTID"
    print_user_links "$username"
  else
    local users
    mapfile -t users < <(get_all_users)
    if [ ${#users[@]} -eq 0 ]; then
      echo -e "${YELLOW}No users found in config.${NC}"; exit 0
    fi
    echo -e "${BOLD}${CYAN}Found ${#users[@]} user(s)${NC}"
    for u in "${users[@]}"; do
      resolve_user "$u"
      [ -z "$R_UUID" ] && continue
      build_links "$u" "$R_UUID" "$R_IP" "$R_CDN" "$R_VMHOST" "$R_RSNI" "$R_PUBKEY" "$R_SHORTID"
      print_user_links "$u"
    done
  fi
  echo ""
}

# ============================================================
#  COMMAND: export
# ============================================================
cmd_export() {
  check_deps
  get_server_ip

  local users
  mapfile -t users < <(get_all_users)
  if [ ${#users[@]} -eq 0 ]; then
    echo -e "${YELLOW}No users found in config.${NC}"; exit 0
  fi

  {
    echo "============================================================"
    echo "  Xray Configs Export"
    echo "  Generated: $(date)"
    echo "  Users: ${#users[@]}"
    echo "============================================================"
    for u in "${users[@]}"; do
      resolve_user "$u"
      [ -z "$R_UUID" ] && continue
      build_links "$u" "$R_UUID" "$R_IP" "$R_CDN" "$R_VMHOST" "$R_RSNI" "$R_PUBKEY" "$R_SHORTID"
      format_user_block "$u"
    done
  } > "$EXPORT_FILE"

  echo -e "${GREEN}Exported ${#users[@]} user(s) to: ${BOLD}${EXPORT_FILE}${NC}\n"
}

# ============================================================
#  Entry point
# ============================================================

# Load saved vars first (setup writes these)
load_saved_vars

COMMAND="${1:-}"
shift || true

case "$COMMAND" in
  setup)  cmd_setup ;;
  create) cmd_create ;;
  print)  cmd_print "${1:-}" ;;
  export) cmd_export ;;
  *)
    echo -e "${RED}Unknown or missing command: '$COMMAND'${NC}\n"
    usage
    ;;
esac
